example = function() {
  library(repboxHtml)
  project_dir = "~/repbox/projects_gha/aejapp_1_2_7"
  repbox_ejd_report_html(project_dir)
  rstudioapi::filesPaneNavigate(paste0(project_dir))

  library(repboxRun)
  steps = repboxRun::repbox_steps_from(file_info = TRUE,static_code = TRUE, art=TRUE,reproduction = TRUE, reg=FALSE, repbox_repdb = TRUE,map = FALSE,html=TRUE)
  #steps = repboxRun::repbox_steps_from(html=TRUE)
  opts = repbox_run_opts(stop.on.error=TRUE,html_opts = repbox_html_opts_just_ejd())
  repboxRun::repbox_run_project(project_dir, lang="stata",steps = steps, opts=opts)

  rstudioapi::filesPaneNavigate(paste0(project_dir,"/reports"))
  rstudioapi::filesPaneNavigate("~/repbox/repboxHtml/R")
}

repbox_copy_images_to_ejd_report = function(project_dir) {
  image_files = list.files(file.path(project_dir, "repbox","www","images"),full.names = TRUE)
  ejd_img_dir = file.path(project_dir,"reports/report_ejd/images")
  dir.create(ejd_img_dir,recursive = TRUE)
  file.copy(image_files, ejd_img_dir)
}

repbox_ejd_report_html = function(project_dir, parcels = list(), opts=repbox_html_opts_just_ejd()) {
  restore.point("repbox_ejd_report_html")

  parcels = repboxDB::repdb_load_parcels(project_dir, c("art", "sup", "stata_run_cmd","stata_file", "stata_cmd","stata_do_run_info","data_file","data_write","data_read"), parcels=parcels)

  if (is.null(parcels$stata_do_run_info)) {
    parcels = make_parcel_stata_do_run_info(project_dir, parcels)
  }
  if (is.null(parcels$data_file)) {
    parcels = make_parcel_data_file_info(project_dir, parcels)
  }


  sup = parcels$sup$sup
  art = parcels$art$art
  art$Journ = toupper(art$journ)
  if (is.null(art$authors)) art$authors = ""
  art$authors = stringi::stri_replace_last_fixed(art$authors,", "," and " )
  art = as.list(art)

  prefix = paste0("")
  options(repbox.url.prefix = prefix)
  project = basename(project_dir)
  time = paste0(Sys.time(), " (UTC)")

  report.frag = readLines(system.file("fragments/ejd.html", package="repboxHtml")) %>% merge.lines()

  do_html = report_do_overview(project_dir, parcels=parcels, link_with_tabs = FALSE)
  do_df = parcels$stata_do_run_info$stata_do_run_info

  if (NROW(do_df)>0) {
    sum = do_df[1,]
    noerr_share_num = ifelse(isTRUE(sum$num_runs > 0),(sum$num_runs_err) / sum$num_runs, NA)
    noerr_share = ifelse(is.na(noerr_share_num),"---",paste0(round(100*noerr_share_num),"%"))
  } else {
    noerr_share = "-- No do files found --"
  }


  data_info = datasets_info_html(project_dir, parcels)
  data_sets_html = data_info$html

  if (any(is.true(do_df$timeout))) {
    timeout_info = "The analyis in a do file took so long that we triggered a timeout and exited the analysis. A timeout can also cause errors in other do files. "
    has_timeout = "Yes"
  } else {
    timeout_info = ""
    has_timeout = "No"
  }

  info_txt = ""
  info_txt  = paste0(info_txt, timeout_info)
  if ( isTRUE((round(noerr_share_num*100) < 100 & noerr_share_num > 0.8) | (NROW(data_info$missing.df)==0 & NROW(data_info$exist.df)>0))) {
    info_txt = paste0(info_txt,"Note that even if a human can reproduce the analysis, often less than 100% of commands run without error in the automatic reproduction. ")
  }
  if (NROW(data_info$missing.df)>0 & NROW(data_info$exist.df)>0) {
    info_txt = paste0(info_txt,"Sometimes the main analysis can be reproduced even if some data sets are missing, e.g. the missing data sets could be raw data files that are not directly needed. On the other hand, existence of a data set file does not imply that the data is indeed there: the data set could be empty or contain simulated data if the original data is confidential or proprietary. The tables below will provide more information.  ")
  }


  num_missing_data_org = sum(!data_info$missing.df$intermediate)
  num_missing_data_all = NROW(data_info$missing.df$intermediate)
  if (num_missing_data_all != num_missing_data_org) {
    num_missing_data = paste0(num_missing_data_org, " - ",num_missing_data_all,"*" )
    info_txt = paste0(info_txt, paste0("<br>*We detected ", num_missing_data_all," missing data sets if we include missing intermediate data sets that were supposed to be generated by Stata code, otherwise just detected ", num_missing_data_org, " missing data sets."))
  } else {
    num_missing_data = num_missing_data_all
  }

  vals = c(art,list(data_url = sup$sup_url,info_txt = info_txt, time=time, re_sum = do_html, data_sets_html=data_sets_html, project=project, has_timeout = has_timeout, timeout_info = timeout_info,  noerr_share=noerr_share, num_misssing_data=num_missing_data, num_existing_data = NROW(data_info$exist.df)))
  content.html = glue::glue(report.frag, .envir=vals)


  # overview
  body = as.character(fluidPage(HTML(content.html)))
  head = repbox_html_header(path.prefix = "../")
  head = paste0(head, "<style> p {max-width: 60em;}</style>")
  html = repbox_html_page(body=body, header=head, title=paste0("Report for ",basename(project_dir)), footer_scripts = NULL)


  if (!dir.exists(paste0(project_dir,"/reports/report_ejd")))
    dir.create(paste0(project_dir,"/reports/report_ejd"),recursive = TRUE)


  writeUtf8(merge.lines(html),paste0(project_dir,"/reports/report_ejd/index.html"))

  # Make do.html

  do_opts = opts
  do_opts$img_inline=FALSE

  body = html_just_do(project_dir,parcels = parcels,opts=do_opts)
  head = repbox_html_header(path.prefix = "../")
  html = repbox_html_page(body=body, header=head, title=paste0(basename(project_dir), " do files"))
  writeUtf8(merge.lines(html),paste0(project_dir,"/reports/report_ejd/do.html"))

  return(parcels)
}



##### OLD CODE BELOW


make.ejd.www.index.page = function(info.file = "~/repbox/repbox_ejd_infos.Rds", www.dir = "~/web/repbox", project.dirs = NULL) {
  restore.point("make.ejd.www.index.page")

  info.df = readRDS(info.file)
  www.projects = list.dirs(www.dir, full.names=FALSE, recursive = TRUE) %>% str.between("/","/")

  if (!is.null(project.dirs)) {
    projects = basename(project.dirs)
    www.projects = intersect(www.projects, projects)
  }

  info.df = info.df %>%
    filter( id %in% www.projects) %>%
    filter( is.true(share.runs.no.error >0)) %>%
    mutate(has.all.data = is.true(data.existing > 0 & data.missing==0)) %>%
    arrange(desc(share.runs.no.error), desc(has.all.data)) %>%
    mutate(html = paste0(
      '<p .ejd_link>',1:n(),". ",round(share.runs.no.error*100),'%, ', data.missing, ' missing data, ',round(size.mb,2)," MB, ", runs,' runs, ', runtime, ' seconds ',
      '<a href="',journ,'/',id,'" target="_blank">',title,' (',journ,",",year,')</a>',
      '</p>'
    ))
  style = "<style> .ejd_link {font-family: Helvetia; padding: 5px;}</style>"


  html = paste0("<body>",style,"\n<ul class='ejd_link'>",
    "<h4>Repbox-EJD Webpages</h4>",
    paste0(info.df$html, collapse="\n"),
    "</ul></body>"
  )
  writeLines(html, file.path(www.dir,"index.html"))
}

copy.all.ejd.www = function(project.dirs, ejd.repbox.dir = "~/web/repbox", overwrite=TRUE) {
  restore.point("copy.all.ejd.www")
  project.dirs = get.ejd.projects(project.dirs)
  res = lapply(seq_along(project.dirs), function(i) {
    project_dir = project.dirs[i]
    cat("\n",i,project_dir)
    copy.ejd.www(project_dir, ejd.repbox.dir, overwrite=overwrite)
  })

}


copy.ejd.www = function(project_dir, ejd.repbox.dir = "~/web/repbox", overwrite=TRUE) {
  restore.point("copy.ejd.www")
  source.dir = file.path(project_dir, "repbox","www_ejd")
  if (!file.exists(source.dir)) return()
  art = readRDS(file.path(project_dir,"meta","ejd_art.Rds"))

  dest.dir = file.path(ejd.repbox.dir,art$journ,art$id)
  if (dir.exists(dest.dir)) {
    if (!overwrite) return()
    remove.dir(dest.dir,must.contain = "/web/repbox")
  }
  try(dir.create(dest.dir,recursive = TRUE,showWarnings = FALSE))
  copy.dir(source.dir, dest.dir)
}


make.all.ejd.html = function(project.dirs=NULL, overwrite=FALSE) {
  project.dirs = get.ejd.projects(project.dirs)
  projects = ""

  project_dir = project.dirs[1]
  project.dirs = project.dirs[114:258]
  for (project_dir in project.dirs) {
    exists = dir.exists(file.path(project_dir,"repbox","www_ejd"))
    if (!exists | overwrite) {
      cat(paste0("\n\nCreate ejd html for ", project_dir))
      try(repbox.ejd.html(project_dir))
      projects= c(projects, basename(project_dir))
    } else {
      exists = file.exists(file.path(project_dir,"repbox","www_ejd","repbox.css"))
      if (!exists) {
        res.dir = system.file("www",package="repboxHtml")
        copy.dir(file.path(res.dir,"shared"), file.path(project_dir,"repbox","www_ejd","shared") )
        file.copy(file.path(res.dir,"do_bottom.js"), file.path(project_dir,"repbox","www_ejd"))
        file.copy(file.path(res.dir,"repbox.css"), file.path(project_dir,"repbox","www_ejd"))

        projects= c(projects, basename(project_dir))

      }
    }

  }
  projects
}


